### PR TITLE
Sb es purchase item

### LINKED ISSUE #10: 8. As a user, I want to mark an item on my shopping list as purchased
AC:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)

### PR DESCRIPTION
**Pull request by espain16**
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Related Issue
closes #10 

## Acceptance Criteria
* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made(i.e. we assume the user does not need to buy the item again for at least 1 day)

## List To Complete Task
- [x] Add button element to shopping component
- [x] Call a function when the button is clicked
- [x] Toggle purchase status when clicked
- [x] Style button based on purchase status
- [x] Verified that style & purchase status change based on a timer
- [x] On click generate new Date.
- [x] Set `last_purchase` state field to new Date.
- [x] Save new item state to db ???
- [x] Check that db item is different from current time
- [x] Calculate time since last purchase
- [x] Verified that style & purchase status change based on the time since last purchase

## Description

We had the fundamental mechanics for AC in place relatively early, but had some real difficulties tightening up the logic to show items as purchased or not purchased.

Our key pieces of data are the `last_purchased` date and `isPurchased` boolean. 
`last_purchased` is a field on an `item`, along with `name`, etc.
`last_purchased` is a UTC date string. It's can be converted into milliseconds from which point you can compare dates and do arithmetic on them.

`isPurchased` is a piece of component state.
`isPurchased` is a boolean. 
- `false` means that the item has not been purchased in the last 24 hours.
- When `isPurchased` is `false`, the "Purchase" button is clickable and its color is blue.
- `true` means that the item has been purchased in the last 24 hours.
- When `isPurchased` is `true`, the "Purchase" button is disabled and its color is orange.

This is the basic logic we were pursuing:
- When an item is added to the list it has not yet been purchased (`isPurchased` = `false`).
- When the `Purchase` button is clicked the `last_purchased` date is updated to the current time and saved to the db. `isPurchased` is set to `true`.

These are the assumptions we had about an item being rendered:
1. When the component is rendered `isPurchased` is assumed to be `false`.
2. The item's `last_purchased` date is checked against the current time (the time when the component is being rendered).
3. If the difference between `last_purchased` and the current time is greater than or equal to 24 hours and `isPurchased` = `true`, `isPurchased` is set to `false` (meaning it has not been purchased and is "purchasable").
4. If the difference between `last_purchased` and the current time is less than 24 hours, no changes are made and rendering continues.

We had a very, very difficult time getting things to work as expected. In the end we found that changing points 3 and 4 above got us the results we wanted.
3. If the difference between `last_purchased` and the current time is less than 24 hours and `isPurchased` = `false`, `isPurchased` is set to `true` (meaning it has been purchased and is not "purchasable").
4. If the difference between `last_purchased` and the current time is greater than 24 hours, no changes are made and rendering continues.

Learning how to document these kinds of problems while in the middle of the worst of them is going to be a key skill. It's very hard to reconstruct here the minutia of all the confusions and  problems we ran into. Mapping each problem or confusion to a particular state of the code base would have been helpful. We tried in a heuristic way in the moment, but that's not recoverable.

Documenting for code reviewers how to test a feature like this has been a major challenge. The mechanics of it are not too brutal, but describing how to do it and make it easy to do is difficult. You'll have to judge if we accomplished it.

## Testing Steps / QA Criteria

Pull the `sb-es-purchase-item` branch.
Run `npm install`.
Run `npm start`.

If needed, clear the user token from your local storage (`localStorage.removeItem(your token here)`).

Use this user token: `deal focus mixup`. You can use the "share list" feature to do this! Yay!

Testing this feature is a bit tricky. So here goes . . .

## Testing The ListItem Component

We have some variables set up just for testing in `src/timeConstants.js`.
The time logic is in `src/lib/getDifferenceInHours.js`.

They represent the month, day, hour, minute, and seconds of a stand-in time (a mocked "now") meaning the time the component is rendered.

An item's last purchased date is displayed in the shopping list. It will have a structure like this:
`2020-04-29T22:41:43.715Z`.

This is a progressive break down of the numbers in that string:

```
year-month-day hour:minutes:seconds.milliseconds
year-mo-dy hr:mn:sc.ms
2020-04-29T22:41:43.715Z
```

T stands for time. Z stands for zulu. Don't get distracted by "T" and "Z". For testing you can probably ignore them. Unless you are a Time Lord. : )

In the `src/timeConstants.js` file you will find the set of test variables:

```
let fakeTimeMonth = `05`;
let fakeTimeDay = `01`;
let fakeTimeHour = `20`;
let fakeTimeMinute = `23`;
let fakeTimeSeconds = `39.368`;

let fakeCurrentTime = `2020-${fakeTimeMonth}-${fakeTimeDay}T${fakeTimeHour}:${fakeTimeMinute}:${fakeTimeSeconds}Z`;
```

We found it easiest to choose and focus on a particular item in the list to test.

Set the month and day variable for one day ahead of your current date.

Set the other variables to the exact same values as displayed in the date of the item you're testing in the shopping list.

This will make `fakeCurrentTime`, your "mocked now", 24 hours later than the `last_purchased` date of the item.

You should see your item as "purchasable" and you can click the button.

Subtract one millisecond from the "seconds.milliseconds" in the `fakeTimeSeconds` variable. So `fakeTimeSeconds = '39.368'` would become `fakeTimeSeconds = '39.367'`

This sets your `fakeCurrentTime` to less than 24 hours past the `last_purchased` date of the item. Your item will be "marked" as purchased. The "purchase" button will be disabled.

To test items against the true current time, remove `fakeCurrentTime` from
`let nowTimeStamp = new Date(fakeCurrentTime).getTime();` in the `src/lib/getDifferenceInHours.js` file.  
 You should now have `let nowTimeStamp = new Date().getTime();` giving you the true "now".

Add new items. Click buttons. Tell us what breaks!

The AC is:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made(i.e. we assume the user does not need to buy the item again for at least 1 day)

You're an angel.

### CODE REVIEW

**Review by SaraSweetie — APPROVED** [review]
Following the instructions, I was able to see the 24-hour change work. I also add two items to the list. I marked one as purchased using the button and the color changed.

From my testing, I would say it's functioning as intended.

**Review by jaysonjphillips — COMMENTED** [review]
My suggestion would be to remove creating a default "last_purchased" date. Since that date shows up, it's a bit confusing in the UI that that was intended. 

Would an empty string or null suffice?

**Comment by jaysonjphillips** [comment]
> My suggestion would be to remove creating a default "last_purchased" date. Since that date shows up, it's a bit confusing in the UI that that was intended.
> 
Approved w/ the reminder of what @segdeha mentioned re: setting a default `last_purchased` on a new item

**Comment by skillitzimberg** [comment]
> > My suggestion would be to remove creating a default "last_purchased" date. Since that date shows up, it's a bit confusing in the UI that that was intended.
> 
> Approved w/ the reminder of what @segdeha mentioned re: setting a default `last_purchased` on a new item

I replaced the default timestamp with an empty string as suggested. It works as expected.

**Pull request merged**
